/**
 * Bundles the Vercel server function into api/index.mjs (committed, so Vercel deploys a
 * plain JavaScript file with no build-time surprises). Run after changing server code:
 *   npm run bundle:api
 * `--check` exits non-zero when the committed bundle is out of date.
 */
import { build, type BuildOptions } from 'esbuild';
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const outfile = resolve('api/index.mjs');
export const bundleOptions: BuildOptions = {
  entryPoints: [resolve('server/vercel.ts')],
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node22',
  write: false,
  outfile,
  metafile: true,
  legalComments: 'none',
  // pg only loads its optional native binding when asked; it is never used here.
  external: ['pg-native'],
  // Bundled CommonJS dependencies (express, pg) call require() for Node built-ins.
  banner: {
    js: "// Generated by scripts/bundle-api.ts from server/vercel.ts. Do not edit.\nimport { createRequire as __cylveroCreateRequire } from 'node:module';\nconst require = __cylveroCreateRequire(import.meta.url);",
  },
};

/** Treats CRLF and LF as equal, so a Windows checkout of the bundle compares cleanly. */
export function normalizeEol(text: string): string {
  return text.replace(/\r\n/g, '\n');
}

export async function bundle(): Promise<string> {
  const result = await build(bundleOptions);
  const inputs = Object.keys(result.metafile!.inputs);
  // The hosted function must never load the local SQLite storage.
  if (inputs.some((input) => input.endsWith('server/store.ts')))
    throw new Error('Vercel bundle must not include the SQLite store');
  return result.outputFiles![0].text;
}

// Compare real paths so direct runs work on Windows too (file:///C:/… vs C:\…).
if (process.argv[1] && fileURLToPath(import.meta.url) === resolve(process.argv[1])) {
  const code = await bundle();
  if (process.argv.includes('--check')) {
    let current = '';
    try {
      current = readFileSync(outfile, 'utf8');
    } catch {
      // missing bundle counts as stale
    }
    // Ignore CR so a CRLF checkout (Windows, core.autocrlf) still counts as up to date.
    if (normalizeEol(current) !== normalizeEol(code)) {
      console.error('api/index.mjs is out of date. Run: npm run bundle:api');
      process.exit(1);
    }
    console.log('api/index.mjs is up to date');
  } else {
    writeFileSync(outfile, code);
    console.log(`Wrote ${outfile} (${Math.round(code.length / 1024)} KB)`);
  }
}
